<a href="https://colab.research.google.com/github/mohamad1371/RL_trader_bot/blob/main/image_classification_with_InceptionResNetV2_transfer_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive/', force_remount=True)

!unzip "/content/drive/MyDrive/dataset.zip" -d "/content/unzip_data/"

Streaming output truncated to the last 5000 lines.
   creating: /content/unzip_data/trainset/9/
  inflating: /content/unzip_data/trainset/9/1e6094d2adc35661c8842d4b4c27e5d139b9ccd3_1612811049.jpg  
  inflating: /content/unzip_data/trainset/9/b096713c0badb47bba93607a903ec4c70e6d7234_1624136699.jpg  
  inflating: /content/unzip_data/trainset/9/d8fbc358b9931e27644a5fd26e06cc19d3a6fac4_1626680441.jpg  
  inflating: /content/unzip_data/trainset/9/d7e3c63e003dbb436cc328cabe0e2dbda3900f36_1620535849.jpg  
  inflating: /content/unzip_data/trainset/9/ed3c7ac01a5530cb0cd7ad958c1adde57d8bc693_1611658647.jpg  
  inflating: /content/unzip_data/trainset/9/3ef8ff5d04ae49b7cb156eb57dd9b11995655d4b_1620800672.jpg  
  inflating: /content/unzip_data/trainset/9/7134ddcaee6ae58f748a046aaf4c093523caee63_1628513932.jpg  
  inflating: /content/unzip_data/trainset/9/a8c2beabe0156b86fdd55735273a0e0d14aa5654_1624478680.jpg  
  inflating: /content/unzip_data/trainset/9/c5943a6ce7ea09dd409a4c26659135dedb07c042_162

In [ ]:
import tensorflow as tf
from keras.models import Sequential, Model
from keras.layers import AveragePooling2D, Flatten, RepeatVector, Reshape, ZeroPadding2D, Input, Dense

In [ ]:
def feature_extractor(inputs):
    feature_extractor_layers = tf.keras.applications.inception_resnet_v2.InceptionResNetV2(
        input_shape=(299, 299, 3),
        include_top = False,
        weights = 'imagenet')
    feature_extractor_layers.trainable = False
    feature_extractor_layers = feature_extractor_layers(inputs)

    return feature_extractor_layers    

In [ ]:
def classifier(inputs):
    x = tf.keras.layers.GlobalAveragePooling2D()(inputs)
    x = tf.keras.layers.Flatten()(x)
    x = tf.keras.layers.Dense(2048, activation = "relu")(x)
    x = tf.keras.layers.Dense(1024, activation = "relu")(x)
    x = tf.keras.layers.Dense(512, activation = "relu")(x)
    x = tf.keras.layers.Dense(10, activation = "softmax", name = 'classification')(x)

    return x

In [ ]:
def final(inputs):

    res_feature_extractor = feature_extractor(inputs)
    classification_output = classifier(res_feature_extractor)

    return classification_output

In [ ]:
inputs = Input(shape=(299, 299, 3))
out_put = final(inputs)

model = Model(inputs, out_put)

219070464/219055592 [==============================] - 2s 0us/step


In [ ]:
# image_dim = 456*456
# model = tf.keras.models.Sequential([
#     # Note the input shape is the desired size of the image 150x150 with 3 bytes color
#     # This is the first convolution
#     tf.keras.layers.Conv2D(64, (3,3), activation='relu', input_shape=(200, 200, 3)),
#     tf.keras.layers.MaxPooling2D(2, 2),
#     # The second convolution
#     tf.keras.layers.Conv2D(128, (3,3), activation='relu'),
#     tf.keras.layers.MaxPooling2D(2,2),
#     # The third convolution
#     tf.keras.layers.Conv2D(256, (3,3), activation='relu'),
#     tf.keras.layers.MaxPooling2D(2,2),
#     # The fourth convolution
#     tf.keras.layers.Conv2D(256, (3,3), activation='relu'),
#     tf.keras.layers.MaxPooling2D(2,2),
#     # The fifth convolution
#     #tf.keras.layers.Conv2D(64, (3,3), activation='relu'),
#     #tf.keras.layers.MaxPooling2D(2,2),
#     # Flatten the results to feed into a DNN
#     tf.keras.layers.Flatten(),
#     # 512 neuron hidden layer
#     tf.keras.layers.Dense(512, activation='relu'),
#     # Only 1 output neuron. It will contain a value from 0-1 where 0 for 1 class ('horses') and 1 for the other ('humans')
#     tf.keras.layers.Dense(10, activation='softmax')
# ])

In [ ]:
model.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 299, 299, 3)]     0         
_________________________________________________________________
inception_resnet_v2 (Functio (None, 8, 8, 1536)        54336736  
_________________________________________________________________
global_average_pooling2d (Gl (None, 1536)              0         
_________________________________________________________________
flatten (Flatten)            (None, 1536)              0         
_________________________________________________________________
dense (Dense)                (None, 2048)              3147776   
_________________________________________________________________
dense_1 (Dense)              (None, 1024)              2098176   
_________________________________________________________________
dense_2 (Dense)              (None, 512)               524800

In [ ]:
from tensorflow.keras.optimizers import RMSprop
from tensorflow.keras.metrics import CategoricalAccuracy

model.compile(loss='categorical_crossentropy',
              optimizer='Adam',
              metrics=[CategoricalAccuracy()])

In [ ]:
from tensorflow.keras.preprocessing.image import ImageDataGenerator

train_data_dir = '/content/unzip_data/trainset'
batch_size = 32
epochs = 30
img_h_and_w = 299

train_datagen = ImageDataGenerator(rescale=1./255,
                                   rotation_range = 30,
                                   width_shift_range = 0.15,
                                   height_shift_range = 0.15,

    shear_range=0.2,
    zoom_range=0.15,
    horizontal_flip=True,
    validation_split=0.2) 

train_generator = train_datagen.flow_from_directory(
    train_data_dir,
    target_size=(img_h_and_w, img_h_and_w),
    batch_size=batch_size,
    class_mode='categorical',
    subset='training') 

validation_generator = train_datagen.flow_from_directory(
    train_data_dir, # same directory as training data
    target_size=(img_h_and_w, img_h_and_w),
    batch_size=batch_size,
    class_mode='categorical',
    subset='validation') 

model.fit_generator(
    train_generator,
    steps_per_epoch = train_generator.samples // batch_size,
    validation_data = validation_generator, 
    validation_steps = validation_generator.samples // batch_size,
    epochs = epochs)

Found 7994 images belonging to 10 classes.
Found 1996 images belonging to 10 classes.


/usr/local/lib/python3.7/dist-packages/keras/engine/training.py:1972: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
  warnings.warn('`Model.fit_generator` is deprecated and '


Epoch 1/30
249/249 [==============================] - 356s 1s/step - loss: 1.6706 - categorical_accuracy: 0.4393 - val_loss: 1.4932 - val_categorical_accuracy: 0.4975
Epoch 2/30
249/249 [==============================] - 306s 1s/step - loss: 1.3887 - categorical_accuracy: 0.5306 - val_loss: 1.4230 - val_categorical_accuracy: 0.5076
Epoch 3/30
249/249 [==============================] - 307s 1s/step - loss: 1.2971 - categorical_accuracy: 0.5687 - val_loss: 1.3134 - val_categorical_accuracy: 0.5580
Epoch 4/30
249/249 [==============================] - 308s 1s/step - loss: 1.2075 - categorical_accuracy: 0.5894 - val_loss: 1.3007 - val_categorical_accuracy: 0.5635
Epoch 5/30
249/249 [==============================] - 309s 1s/step - loss: 1.1533 - categorical_accuracy: 0.6107 - val_loss: 1.3087 - val_categorical_accuracy: 0.5655
Epoch 6/30
249/249 [==============================] - 310s 1s/step - loss: 1.1064 - categorical_accuracy: 0.6206 - val_loss: 1.3291 - val_categorical_accuracy: 0.557

In [ ]:

model.save('classifier_model.h5') 
del model  


In [ ]:
from keras.models import load_model
model = load_model('classifier_model.h5')

/usr/local/lib/python3.7/dist-packages/keras/layers/core.py:1045: UserWarning: keras.applications.inception_resnet_v2 is not loaded, but a Lambda layer uses it. It may cause errors.
  , UserWarning)


In [ ]:
import numpy as np
from google.colab import files
from keras.preprocessing import image

import cv2
import os

images = []
folder_path = '/content/test'

for img in os.listdir(folder_path):
    img = os.path.join(folder_path, img)
    img = image.load_img(img, target_size=(299, 299))
    img = image.img_to_array(img)
    img = np.expand_dims(img, axis=0)
    images.append(img)

# stack up images list to pass for prediction
images = np.vstack(images)
classes = model.predict(images, batch_size=10)
print(classes)

[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
import pandas as pd
names = []
for i in os.listdir(folder_path):
    names.append(i)

a = np.array(classes)
cc = np.argmax(a, axis=1)

prs = []
for i in cc:
    
    prs.append(i+1)


dic = {'name':names, 'predicated':prs}

df = pd.DataFrame(dic)
df.to_csv('results.csv', index = False)